# Generated by Django 5.1.5 on 2025-01-25 09:16

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='But',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('len_member', models.IntegerField(verbose_name='ظرفیت')),
                ('gender_type', models.CharField(choices=[('male', 'پسرونه'), ('female', 'دخترونه')], default='female', max_length=20, verbose_name='جنسیت')),
                ('description', models.TextField(default='', verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'خوابگاه',
                'verbose_name_plural': 'خوابگاه ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('but', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butapp.but')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='اسم')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('student_code', models.CharField(max_length=20, verbose_name='شماره دانشجویی')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('parent_mobile_number', models.CharField(max_length=20, verbose_name='شماره تلفن والدین')),
                ('nation_code', models.CharField(max_length=20, unique=True, verbose_name='شماره ملی')),
                ('grade', models.IntegerField(verbose_name='سال ورودی')),
                ('field', models.CharField(max_length=100, verbose_name='رشته')),
                ('location', models.CharField(max_length=100, verbose_name='شهر سکونت فرد')),
                ('gender', models.CharField(choices=[('male', 'پسرونه'), ('female', 'دخترونه')], default='female', max_length=20)),
                ('status', models.CharField(choices=[('در حال بررسی', 'در حال بررسی'), ('رد شده', 'رد شده'), ('تایید شده', 'تایید شده')], default='در حال بررسی', max_length=20, verbose_name='وضعیت')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('but', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='butapp.but')),
            ],
            options={
                'verbose_name': 'فرم خوابگاه',
                'verbose_name_plural': 'فرم خوابگاه',
            },
        ),
    ]
