# Generated by Django 5.1.5 on 2025-01-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='but',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='butapp.but'),
        ),
        migrations.AlterField(
            model_name='studentdormitory',
            name='but',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='butapp.but', verbose_name='خوابگاه'),
        ),
    ]
