# Generated by Django 5.1.5 on 2025-01-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butapp', '0002_alter_image_but_alter_studentdormitory_but'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdormitory',
            name='status',
            field=models.CharField(choices=[('در حال بررسی', 'درخواست در حال بررسی : درخواست ثبت نام شما در حال بررسی می\u200cباشد ، لطفا تا زمان بررسی درخواست شکیبا باشید'), ('رد شده', 'درخواست رد شده : درخواست شما از طرف کارشناس امور خوابگاه ها رد شده است ، جهت پیگیری در تایم اداری با شماره ۰۱۱۴۴۴۴۲۱۳۵ با داخلی ۱۴۹ تماس حاصل فرمایید'), ('تایید شده', 'درخواست قبول شده : وضعیت درخواست ثبت نام شما در مرحله قبول شده می\u200cباشد ، لطفا در زمان اعلامی از طرف دانشگاه نسبت به نهایی کردن ثبت نام خود اقدام نمایید')], default='در حال بررسی', max_length=20, verbose_name='وضعیت'),
        ),
    ]
