# Generated by Django 5.1.5 on 2025-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butapp', '0004_alter_studentdormitory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='but',
            name='gender_type',
            field=models.CharField(choices=[('پسرونه', 'پسرونه'), ('دخترونه', 'دخترونه')], default='دخترونه', max_length=20, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='studentdormitory',
            name='gender',
            field=models.CharField(choices=[('پسرونه', 'پسرونه'), ('دخترونه', 'دخترونه')], default='دخترونه', max_length=20),
        ),
    ]
