# Generated by Django 5.1.5 on 2025-02-01 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butapp', '0005_alter_but_gender_type_alter_studentdormitory_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdormitory',
            name='but',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='butapp.but', verbose_name='خوابگاه'),
        ),
    ]
