# Generated by Django 5.1.5 on 2025-02-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butapp', '0007_homepageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(upload_to='images/Home'),
        ),
    ]
