# Generated by Django 5.1.5 on 2025-02-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butapp', '0009_alter_homepageimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitybut',
            name='number',
            field=models.IntegerField(default=0, verbose_name='تعداد ظرفیت بافی مانده'),
        ),
    ]
